### ISSUE TITLE
Image based changes for Flow > Conditions article

### ISSUE THREAD

**Issue by iamletmethink** [Stencyl/stencylpedia#11]
I don't have the ability to change images (afaik), I'll post here with some updated images.

Currently in the Flow -> Loops article, this image is used.
![loop-count-example](http://static.stencyl.com/pedia2/blocks/flow/flow_looping/DefiniteLoopExample1.png)
I suggest replacing it with this image instead, since it is an outdated image from pre 2.0 Stencyl.
![repeatcorrectimage](https://cloud.githubusercontent.com/assets/13985596/10862996/86e20286-7fb6-11e5-946c-ed6aafc68442.png)

The image later down in the article is actually impossible to do as easily in Stencyl now.
![repeat-example](http://static.stencyl.com/pedia2/blocks/flow/flow_looping/IndefiniteLoopExample2.png)
This would involve a change of the block itself (like defining index0 at the start, and then incrementing it each frame. I imagine the blocks provided code something like this:
```haxe
_Answer = 0;
var index0 = 0;
while(!((_Answer > 10)))
{
	_Answer += index0;
	propertyChanged("_Answer", _Answer);
	index0++;
}
trace(_Answer);
```

The image for returning to start of loop is slightly outdated (and blurry?).
![return-example](http://static.stencyl.com/pedia2/blocks/flow/flow_looping/StoppingExample3.png)
Here is an updated one:
![return-to-start-of-loop-example](https://cloud.githubusercontent.com/assets/13985596/10863056/08d68134-7fb9-11e5-8cdf-e4db36425edc.png)

**Comment by jon914** [comment]
Hmm, don't you find it odd that the gray print block at the bottom of the last example has a little gap above it?

**Comment by iamletmethink** [comment]
I generated it using the 'copy to image' function. However, if need be, I'll just take a screenshot since it displayed correctly in the actual app. It may have been when I made it transparent that this occured

**Comment by jon914** [comment]
That would be great. I'm going to tweak the other example - good catch on that that I didn't realize.

**Comment by jon914** [comment]
I ended up changing the example over to Fibonacci rather than try to stick with the old one.

**Comment by iamletmethink** [comment]
![example](https://cloud.githubusercontent.com/assets/13985596/10892208/1008cb6e-819a-11e5-8ec6-c72db9734557.png)

Sorry for lateness - here's the fixed image

**Comment by jon914** [comment]
Thanks, I've put it in.
