### ISSUE TITLE
Image changes for Numbers & Text > Text article

### ISSUE THREAD

**Issue by iamletmethink** [Stencyl/stencylpedia#13]
Currently, the images at the bottom of the article are wrong. The second bottom image is of a block which no longer exists in Stencyl. The bottom block should instead be this block:

![text height](https://cloud.githubusercontent.com/assets/13985596/10865215/97202038-7ffc-11e5-8537-f96d7b5fb647.png)

**Comment by jon914** [comment]
Fixed.
