### ISSUE TITLE
Wrong link for 'Extend the Toolset'

### ISSUE THREAD

**Issue by iamletmethink** [Stencyl/stencylpedia#15]
![wrong link](https://cloud.githubusercontent.com/assets/13985596/10894741/4eb9c080-81a8-11e5-8619-2442c37aa93f.PNG)
Clicking 'view more' here opens this page:
http://www.stencyl.com/developers/haxe/
When ideally it should open this link:
http://www.stencyl.com/help/view/creating-extensions/

**Comment by jon914** [comment]
Fixed.
